
site_name: spacerover documentation

theme:
  name: null
  custom_dir: 'cinder'

nav:
  - Home: index.md
  - Releases: 
    - Overview: releases\overview.md
    - 1.0.0: releases\1.0.0.md
  - Python: python.md
  - Architecture: 
    - Overview: architecture\overview.md
    - Diagrams: architecture\diagrams.md
  - MkDocs: mkdocs.md
  - Contribute: contribute.md

extra:
  collapse_toc: true