@startuml packages
set namespaceSeparator none
package "spacerover" as spacerover {
}
package "spacerover.main" as spacerover.main {
}
package "spacerover.obstacle" as spacerover.obstacle {
}
package "spacerover.pygame_wrapper" as spacerover.pygame_wrapper {
}
package "spacerover.root_window_pygame" as spacerover.root_window_pygame {
}
package "spacerover.rover" as spacerover.rover {
}
spacerover.main --> spacerover.root_window_pygame
spacerover.root_window_pygame --> spacerover.obstacle
spacerover.root_window_pygame --> spacerover.pygame_wrapper
spacerover.root_window_pygame --> spacerover.rover
@enduml
