@startuml packages
set namespaceSeparator none
package "spacerover" as spacerover {
}
package "spacerover.map" as spacerover.map {
}
package "spacerover.root_window" as spacerover.root_window {
}
package "spacerover.rover" as spacerover.rover {
}
package "spacerover.rover_movement" as spacerover.rover_movement {
}
package "spacerover.spacerover" as spacerover.spacerover {
}
spacerover --> spacerover.map
spacerover --> spacerover.root_window
spacerover --> spacerover.rover
spacerover.root_window --> spacerover.map
spacerover.root_window --> spacerover.rover
spacerover.rover --> spacerover.map
spacerover.spacerover --> spacerover.root_window
@enduml
