name: Release

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Check-out repository
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip3 install build
          pip3 install pyinstaller
          pip3 install flake8 pytest

      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
  
      # - name: Build package
      #   run: |
      #     cd ..
      #     python -m spacerover

      # - name: Test with pytest
      #   run: |
      #     pytest

      - name: Build exe from Python Script
        run: |         
          pyinstaller --onefile setup.py --name spacerover --noconsole

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          # name: spacerover
          path: dist/*
